### ISSUE TITLE
Scrape to find latest data

### ISSUE THREAD

**Issue by ajtucker** [ONS-OpenData/ONS_BoP_individual-country-data#1]
A new release is due this month (July). The transform should first scrape the web pages to find the latest data.

**Comment by mikeAdamss** [comment]
fixed the technical bits (to the best of my knowledge).

I think failure is around cord references that aren't there anymore but used to be. Needs a look.

let me know id there's anything else I can do on this.

**Comment by ajtucker** [comment]
Thanks @mikeAdamss , it all looks good. The cord references are raised in #2 , so will close this issue and deal with them separately.
