### ISSUE TITLE
GSS_data/Trade/ONS_BoP_individual_countries #22 failed

### ISSUE THREAD

**Issue by ajtucker** [ONS-OpenData/ONS_BoP_individual-country-data#2]
Build 'GSS_data/Trade/ONS_BoP_individual_countries' is failing!

Last 50 lines of build output:

```
[...truncated 413 lines...]
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/FI
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/FR
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/PF
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/MK
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GA
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GM
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GE
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/DE
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GH
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GI
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GR
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GL
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GD
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GU
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GT
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GN
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GW
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GY
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/HT
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/HM
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/HN
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/HK
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/HU
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/IS
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/IN
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/ID
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/IR
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/IQ

[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // script
[Pipeline] }
$ docker stop --time=1 f04464fefc749f16a2c0cc1cccbc1f2ac593d039168824ea0cc010a67319c992
$ docker rm -f f04464fefc749f16a2c0cc1cccbc1f2ac593d039168824ea0cc010a67319c992
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Publish)
Stage "Publish" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] script
[Pipeline] {
[Pipeline] step

```

Changes since last successful build:
- [mikelovesbooks] 994acb2153de5836a38e7d2db69796ffe91da987 - updated scraper to use site search

- [mikelovesbooks] 021ba300d4b34aa4ec99b276a2a7bd175c7d660e - finalised scraper, switched to main.py

- [mikelovesbooks] a303ca2c07bf0e7939c53a93eda945c31675da7a - updated Jeninsfile

No changes
No changes
- [mikelovesbooks] 63a5e91dd137a4f2ed40434495abf4502dfa5417 - added schema generation

- [mikelovesbooks] af79638f58d98327b0eaa5ebb8ca79a911ec467a - add gssutils import

- [mikelovesbooks] 67bff6ae1151d12738a49b2d00e019fd9c203d28 - correct import statment

- [mikelovesbooks] eb1c30f58b90d5e98c21fe139d4c373ccf2532e1 - add out path

- [mikelovesbooks] 2d5d1e1be8e4b4358b156c33c0f255e66e0175e3 - lower cased import/export, added out path

- [mikelovesbooks] c00b28e9d38d926f80d841f8e60026491b22d491 - update to template for jenkins

[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS_BoP_individual_countries/22/)

**Comment by mikeAdamss** [comment]
related to https://github.com/GSS-Cogs/ONS_BoP_individual-country-data/issues/1

will fix, ignore.

**Comment by ajtucker** [comment]
Build 'GSS_data/Trade/ONS_BoP_individual_countries' is failing!

Last 50 lines of build output:

```
[...truncated 418 lines...]
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/FI
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/FR
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/PF
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/MK
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GA
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GM
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GE
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/DE
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GH
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GI
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GR
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GL
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GD
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GU
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GT
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GN
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GW
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/GY
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/HT
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/HM
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/HN
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/HK
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/HU
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/IS
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/IN
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/ID
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/IR
http://gss-data.org.uk/def/concept/ons-trade-areas-cord/cord/IQ

[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // script
[Pipeline] }
$ docker stop --time=1 90c9123b13343b64fcae0d5df98207ea5c01e1c9481a7d8c5d2b475fb813c2a7
$ docker rm -f 90c9123b13343b64fcae0d5df98207ea5c01e1c9481a7d8c5d2b475fb813c2a7
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Publish)
Stage "Publish" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] script
[Pipeline] {
[Pipeline] step

```

Changes since last successful build:
- [mikelovesbooks] 994acb2153de5836a38e7d2db69796ffe91da987 - updated scraper to use site search

- [mikelovesbooks] 021ba300d4b34aa4ec99b276a2a7bd175c7d660e - finalised scraper, switched to main.py

- [mikelovesbooks] a303ca2c07bf0e7939c53a93eda945c31675da7a - updated Jeninsfile

No changes
No changes
- [mikelovesbooks] 63a5e91dd137a4f2ed40434495abf4502dfa5417 - added schema generation

- [mikelovesbooks] af79638f58d98327b0eaa5ebb8ca79a911ec467a - add gssutils import

- [mikelovesbooks] 67bff6ae1151d12738a49b2d00e019fd9c203d28 - correct import statment

- [mikelovesbooks] eb1c30f58b90d5e98c21fe139d4c373ccf2532e1 - add out path

- [mikelovesbooks] 2d5d1e1be8e4b4358b156c33c0f255e66e0175e3 - lower cased import/export, added out path

- [mikelovesbooks] c00b28e9d38d926f80d841f8e60026491b22d491 - update to template for jenkins

- [Alex Tucker] ef905fd5f2db85565dc4eb0bde049534e4846b0f - Use --no-verbose to cut down line length of csvlint output, so it can be



[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS_BoP_individual_countries/23/)

**Comment by ajtucker** [comment]
Build 'GSS_data/Trade/ONS_BoP_individual_countries' is failing!

Last 50 lines of build output:

```
[...truncated 140 lines...]
  File "/usr/local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
Final_table['ONS Partner Geography'] = 'Final_table['ONS Partner Geography']
------------------

[0;36m  File [0;32m"<ipython-input-64-4ba095c41f54>"[0;36m, line [0;32m1[0m
[0;31m    Final_table['ONS Partner Geography'] = 'Final_table['ONS Partner Geography'][0m
[0m                                                           ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax

SyntaxError: invalid syntax (<ipython-input-64-4ba095c41f54>, line 1)

[Pipeline] }
[Pipeline] // ansiColor
[Pipeline] }
[Pipeline] // script
[Pipeline] }
$ docker stop --time=1 91997bf03abd7db9d69c5b187f23b2ef13c3f13f0291717701d64f98435bcf9a
$ docker rm -f 91997bf03abd7db9d69c5b187f23b2ef13c3f13f0291717701d64f98435bcf9a
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Validate CSV)
Stage "Validate CSV" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Upload Tidy Data)
Stage "Upload Tidy Data" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Test draft dataset)
Stage "Test draft dataset" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Publish)
Stage "Publish" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] script
[Pipeline] {
[Pipeline] step

```

Changes since last successful build:
- [mikelovesbooks] 994acb2153de5836a38e7d2db69796ffe91da987 - updated scraper to use site search

- [mikelovesbooks] 021ba300d4b34aa4ec99b276a2a7bd175c7d660e - finalised scraper, switched to main.py

- [mikelovesbooks] a303ca2c07bf0e7939c53a93eda945c31675da7a - updated Jeninsfile

No changes
No changes
- [mikelovesbooks] 63a5e91dd137a4f2ed40434495abf4502dfa5417 - added schema generation

- [mikelovesbooks] af79638f58d98327b0eaa5ebb8ca79a911ec467a - add gssutils import

- [mikelovesbooks] 67bff6ae1151d12738a49b2d00e019fd9c203d28 - correct import statment

- [mikelovesbooks] eb1c30f58b90d5e98c21fe139d4c373ccf2532e1 - add out path

- [mikelovesbooks] 2d5d1e1be8e4b4358b156c33c0f255e66e0175e3 - lower cased import/export, added out path

- [mikelovesbooks] c00b28e9d38d926f80d841f8e60026491b22d491 - update to template for jenkins

- [Alex Tucker] ef905fd5f2db85565dc4eb0bde049534e4846b0f - Use --no-verbose to cut down line length of csvlint output, so it can be

- [mikelovesbooks] 089c3d8a21c0c16783c6fc55c4b8f8e2b0994785 - remove cord/ prefix from ONS partner geography



[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS_BoP_individual_countries/24/)

**Comment by ajtucker** [comment]
Build 'GSS_data/Trade/ONS_BoP_individual_countries' is failing!

Last 50 lines of build output:

```
[...truncated 140 lines...]
  File "/usr/local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
Final_table['ONS Partner Geography'] = 'Final_table['ONS Partner Geography'
------------------

[0;36m  File [0;32m"<ipython-input-64-ea4fde9209ee>"[0;36m, line [0;32m1[0m
[0;31m    Final_table['ONS Partner Geography'] = 'Final_table['ONS Partner Geography'[0m
[0m                                                           ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax

SyntaxError: invalid syntax (<ipython-input-64-ea4fde9209ee>, line 1)

[Pipeline] }
[Pipeline] // ansiColor
[Pipeline] }
[Pipeline] // script
[Pipeline] }
$ docker stop --time=1 de9c0823f65817f3e2146e89b523b022995a6efca82384f5fe7d29d6a189ad7f
$ docker rm -f de9c0823f65817f3e2146e89b523b022995a6efca82384f5fe7d29d6a189ad7f
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Validate CSV)
Stage "Validate CSV" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Upload Tidy Data)
Stage "Upload Tidy Data" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Test draft dataset)
Stage "Test draft dataset" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Publish)
Stage "Publish" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] script
[Pipeline] {
[Pipeline] step

```

Changes since last successful build:
- [mikelovesbooks] 994acb2153de5836a38e7d2db69796ffe91da987 - updated scraper to use site search

- [mikelovesbooks] 021ba300d4b34aa4ec99b276a2a7bd175c7d660e - finalised scraper, switched to main.py

- [mikelovesbooks] a303ca2c07bf0e7939c53a93eda945c31675da7a - updated Jeninsfile

No changes
No changes
- [mikelovesbooks] 63a5e91dd137a4f2ed40434495abf4502dfa5417 - added schema generation

- [mikelovesbooks] af79638f58d98327b0eaa5ebb8ca79a911ec467a - add gssutils import

- [mikelovesbooks] 67bff6ae1151d12738a49b2d00e019fd9c203d28 - correct import statment

- [mikelovesbooks] eb1c30f58b90d5e98c21fe139d4c373ccf2532e1 - add out path

- [mikelovesbooks] 2d5d1e1be8e4b4358b156c33c0f255e66e0175e3 - lower cased import/export, added out path

- [mikelovesbooks] c00b28e9d38d926f80d841f8e60026491b22d491 - update to template for jenkins

- [Alex Tucker] ef905fd5f2db85565dc4eb0bde049534e4846b0f - Use --no-verbose to cut down line length of csvlint output, so it can be

- [mikelovesbooks] 089c3d8a21c0c16783c6fc55c4b8f8e2b0994785 - remove cord/ prefix from ONS partner geography

- [mikelovesbooks] de9b7351c04d5c9faac95e9859396e45a7d3e47a - remove bad syntax



[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS_BoP_individual_countries/25/)

**Comment by grace-spitzer-wong** [comment]
https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS_BoP_individual_countries/23/

extra cord spotted by Mike

**Comment by ajtucker** [comment]
Build was fixed!
